### ISSUE TITLE
Uncompatible asset file (blocksJ2B.json) for 1.20.6

### ISSUE THREAD

**Issue by jerryqiu2008** [JaylyDev/nbt-to-mcstructure#13]
Some errors in bedrock blocks' format:
  1. All kinds of woods: "minecraft:log2[new_log_type=dark_oak,pillar_axis=x]" should be "minecraft:dark_oak_log[pillar_axis=x]"
  2. Lack of new blocks: e.g. CherryWoods

**Comment by JaylyDev** [comment]
Thanks for reporting. Updated to be compatible with 1.20.6 / 1.20.80, try now.
